### PR TITLE
Add plot calendar and refactor plot map

### PR DESCRIPTION
**Pull request by mihagazvoda**
Added `plot_calendar` functions and refactored `plot_map`.

### CODE REVIEW

**Comment by marcusvolz** [comment]
Thanks again Miha

**Comment by narfel** [comment]
Thanks to you both for that fine work. If i may, i'd be interested in that circle packing as well.

**Comment by mihagazvoda** [comment]
@narfel thanks for your suggestion. @marcusvolz Can you share your code for packed circles? I can implement it into a package.

**Comment by marcusvolz** [comment]
See the following Gist for the packed circles code: https://gist.github.com/marcusvolz/74648099f0084d5065d1919586963bab. If you would like to implement it into the package it would be appreciated :)

**Comment by mihagazvoda** [comment]
@narfel @marcusvolz done :)

**Pull request merged**
