### PR TITLE
Added 3D elevation plot - Fixes #47

### LINKED ISSUE #47: Add 3D visualization using rayshader package
As discussed under #38 i will try to pull together a proto for this.
First just one tracklog in a 3D elevation scene.

### PR DESCRIPTION
**Pull request by BalintKomjati**
Running `strava::plot_3D` will generate the following demo plot:

image

I added a new tracklog gpx with hilly scene to make the demo more appealing. I put it into a separate folder (gpx/mtb) because process_data() reads in all tracks from a folder without explicit reference to the file, only an arbitrary id number, making it uncertain if the demo will read the hilly gpx.

### CODE REVIEW

**Comment by marcusvolz** [comment]
@BalintKomjati This looks amazing! I will test on my own data in the next few days.

**Comment by BalintKomjati** [comment]
This does not look very good... i am on it

**Comment by BalintKomjati** [comment]
UX and macOS tests failed - i will try to fix it in my forked repo.

**Comment by BalintKomjati** [comment]
Hello @marcusvolz and @datawookie! 
Could you please help me fixing the install checks? 
I am sure this is caused by the new dependency packages needed for the 3D plot above.

Windows passed before, i managed to fix the Ubuntu (release) run by adding the necessary OS components into the check.yaml of the R packages 'terra' and 'magick'. 

I guess the same is needed for MacOS but i have no experience with this OS...

And I am out of ideas for the Ubuntu (devel) which fails because "there is no package called ‘terra’".

Putting me into the right direction with hints could also be a great help :)

thanks

Bálint

**Comment by marcusvolz** [comment]
@datawookie would you mind taking a look at this if you are around and have time? I am not fully up to speed on the new workflows yet.

**Comment by BalintKomjati** [comment]
> @datawookie would you mind taking a look at this if you are around and have time? I am not fully up to speed on the new workflows yet.

Hi @datawookie did you have the chance to review this PR?
https://github.com/BalintKomjati/strava/actions/runs/1492301193
Here are the check logs showing Win and Ubuntu are passed but Ubuntu(devel) and MacOS failed for some reason I could not figure out ...

**Comment by datawookie** [comment]
Hi @BalintKomjati, I've sorted out the tests. See https://github.com/BalintKomjati/strava/pull/2 on your repository. If you accept those changes then we can accept this PR too. Thanks, Andrew.

**Comment by BalintKomjati** [comment]
Thank you so much @datawookie! I accepted the PR in my repository.

**Comment by marcusvolz** [comment]
@BalintKomjati @datawookie Let me know if there's anything you need from me to get this into the main repo. I'd be keen to test out the plot_3D function on my own data.

**Comment by datawookie** [comment]
Hi @BalintKomjati, I've just run the GitHub Action with the package checks and it appears to be failing on the Windows platform. Could you please take a look at that and try to resolve the issue? Shout if you need any help. Thanks, Andrew.

**Comment by BalintKomjati** [comment]
Hi @datawookie @marcusvolz!
To be fairly honest I kind of lost track of what is happening because different tests fail depending on the time we ran them. My best bet is that this is due to new releases of the imports / depends. 

Yes, lately only Win fails (https://github.com/BalintKomjati/strava/actions/runs/1741925794). Google searches mainly just suggest to restart / reinstall everything or change the order of imports but nothing about the root cause of the error message:

_Error: Error: Function found when exporting methods from the namespace 'raster' which is not S4 generic: 'all.equal'_

On a separate branch I tried a few not-so-educated guesses but i could not resolve the issue.
https://github.com/BalintKomjati/strava/tree/plot3d-fix-checks

So @datawookie I would be grateful to have you take a look as well!

**Comment by BalintKomjati** [comment]
Hi All! 

I just rerun the checks on @datawookie 's last commit [804488e](https://github.com/BalintKomjati/strava/commit/804488e377539368a9e2b0d6fe69a7ba1a18b2f8) and it is all passed now :)

See: https://github.com/BalintKomjati/strava/actions/runs/1741925794

@marcusvolz can you pls rerun the test for this PR and if all good accept?

Cheers,
Bálint

**Review by datawookie — APPROVED** [review]
Looks good and all tests pass! :tada:

**Comment by datawookie** [comment]
Thanks for your patience and perseverance with this, @BalintKomjati. Merging right now!

**Comment by marcusvolz** [comment]
Thank you both! Looking forward to testing this out!

**Comment by BalintKomjati** [comment]
It is my pleasure :)

**Pull request merged**
