### PR TITLE
Expanded functionality

### PR DESCRIPTION
**Pull request by Vosbrucke**
Hi, I created some new functions to the package. Most of them are based on activities.csv file but there are also some changes to already existing functions. At first I started with the idea to implement colors by activity type in plot_facets and then to explore further possibilities with the data. Bear in mind that I heard about R only a couple months ago so there may be some things which could have been made much easier and faster. Please, feel free to make or suggest changes.

### CODE REVIEW

**Comment by Vosbrucke** [comment]
I changed it. Is it ok now?

**Comment by hugovk** [comment]
Thanks! I'll let others who are more familiar with R review the actual code.

**Comment by marcusvolz** [comment]
I will review on the weekend, thank you!

**Comment by marcusvolz** [comment]
@Vosbrucke Thank you for the new visualizations and updates to existing visualizations, they look great!

I have reviewed the code briefly and it looks good to me, although I have not had to chance yet to create the plots with my own data.

I note that a Google Maps API key is required to create the individual plot map. Perhaps you could add to the readme user instructions on how to do this.

@datawookie @mihagazvoda If either of you have time and would be interested to review this PR it would be appreciated! Otherwise I'm happy to merge.

**Comment by Vosbrucke** [comment]
@marcusvolz Thanks for the response. 

You are right about the API key. I have made changes to README file where I added info on how to access Google API key and what possibilities functions dependent on the output of process_activities have. 

I am also thinking about providing example data but this is something I will do in the future.

**Pull request merged**
